### ISSUE TITLE
Joyful calendar "Today"

### ISSUE THREAD

**Issue by ghost** [linuxsoftware/ls.joyful#1]
Hi,
How can the "Today" button be enabled on the calendar ?
It appears to be disabled by default.
My bad, its disabled in the current month view.

**Comment by ghost** [comment]
I was looking for a listing of today's events

**Comment by linuxsoftware** [comment]
Try the following to get a 'Day view'.  Sorry, I have not tested this code, so it might not be quite right.

```
from ls.joyful.models import FullCalendarPage
FullCalendarPage._meta.get_field('view_choices').choices = [
                       ('L', "List View"),
                       ('W', "Weekly View"),
                       ('M', "Monthly View"),
                       ('D', "Daily View")]

```

I think this will add a Daily View option under the Settings tab of your calendar, which can then be enabled.

Let me know if you have trouble and I'll take a closer look.

**Comment by ghost** [comment]
Hi David,

Thanks for the reply,
I am a complete beginner when it comes to code.  
I could not find where to insert your solution.
However after searching through the plugin I modified joyous/models/calendar.py

EVENTS_VIEW_CHOICES = [('L', _("List View")),
                       ('W', _("Weekly View")),
                       ('M', _("Monthly View")),
                       ('D', _("Daily View")),
                       ]
    view_choices = MultipleSelectField(_("view choices"), blank=True,
                                       default=["L","W","M","D"],
                                       choices=EVENTS_VIEW_CHOICES)





To my complete surprise this worked !! 
I have the option of selecting the “day” in the calendar settings.

If I have done something wrong could you point me to the file that I should of modified with your solution.

Thanks

Terence Desborough

38 Narcamus Crescent
Shailer Park Q 4128
Ph: 0409 059 461
email:  ***@***.***

**Comment by linuxsoftware** [comment]
Hi Terence,

Glad that worked for you.  The problem with directly changing the ls.joyous source files is those files will be overwritten if you upgrade or re-install Joyous and then you'll have to make the changes again.  If you're happy with that, then no problem, go with that.

Otherwise, the code I suggested was meant to go in one of your own applications.  Either in a models.py or wagtail_hooks.py file.  Sorry I didn't make that clear.  And, if your Wagtail project has multiple applications then any one of them will do, just pick the application that makes the most sense (e.g. if you have an events application it could go there.)

Hope that helps.

**Comment by ghost** [comment]
Hi David,
Thanks for that, I would rather not touch the source files and I’ll try your method.
I am attempting to build a client booking app for a home cleaning service and joyous was the only plug-in I could find with recurring events. The others weren’t very well documented for beginner’s but I am enjoying myself. My personal challenge is to build the client model that can save the data to the calendar. I would prefer to use a web based form instead of going into wagtail admin to add events.
I really appreciate your help.

Thanks 
Terry
